fm = load('floque.B.out');
fm = fm';
[v e] = eig(fm);
ee = sum(e)';
vv1 = v(:,1);
vv1 = vv1 / sum(vv1);
vv =v(:,1:5);
vv(:,1) = vv1;
save ('floquet.eigvalue.out', 'ee');
save ('floquet.eigvector.out', 'vv');
